<?php
class bloglp{
	var $b_blog="revista";
	var $b_mine="Mi registro";
	var $b_friend="Amigos de registro";
	var $b_creat="Nueva sesión";
	var $b_edit="editor";
	var $b_lock="El registro se ha bloqueado";
	var $b_search="Entrar Buscar";
	var $b_re_list="Volver a la lista de registros";
	var $b_scan="Ver registro";
	var $b_add_suc="Con éxito se comprometan registro";
	var $b_add_fal="La no presentación del registro, por favor vuelva a enviar";
	var $b_edit_suc="El éxito de cambios!";
	var $b_edit_false="Modificar el fallo de registro!";
	var $b_del_suc="Eliminar el éxito del registro";
	var $b_del_false="No se pudo eliminar el registro!";
	var $b_no_pass="Por favor llene cada opción";
	var $b_manage_sort="Categorías del blog";
	var $b_def_sort="Default Category (no es compatible con la edición y el borrado)";
	var $b_del_sort_suc="Eliminar clasificación éxito";
	var $b_change_sort_suc="Modificar la clasificación éxito";
	var $b_change_sort_false="No se pudo modificar la clasificación";
	var $b_only_fri_com="Sólo las del autor Comentarios";
	var $b_not_com="Este registro no puede comentar";
	var $b_num="Los blogs tienen {num}";
	var	$b_title="título";
	var $b_sort="clasificación";
	var $b_author="autor";
	var $b_default_sort="Default Category";
	var $b_com_num="comentario({b_com_num})";
	var $b_read_num="leer({b_read_num})";
	var $b_no_fri_blog="Lo sentimos, no puedes ver el registro actual";
	var $b_del="borrar";
	var $b_a_del="borrar?";
	var $b_button_save="guardar";
	var $b_button_cancel="cancelar";
	var $b_none="Usted no ha añadido registro,<a href='modules.php?app=blog_edit'>Crear un registro de</a>,o<a href='modules.php?app=blog_friend'>Ver Amigos registro</a>";
	var $b_limit="competencia";
	var $b_same_sort="Consulte con la clasificación del registro";
	var $b_public="público";
	var $b_private="Sólo su propio";
	var $b_pals="sólo amigos";
	var $b_error="La información que usted visita la página no existe";
	var $b_empty="Por favor, complete la información";
	var $b_limit_blog="Dado que los fije los permisos de registro, no se puede acceder a";
	var $b_they_com="Opiniones de los usuarios";
	var $b_send_time="Publicado el:{date_time}";
	var $b_i_com="Quiero comentar";
	var $b_button_re="responder";
	var $b_button_clear="eliminar";
	var $b_add_sort="Añadir categorías";
	var $b_content="contenido";
	var $b_pic="imagen";
	var $b_sel_album="（Seleccione Imagen cargada directamente desde el álbum）";
	var $b_button_sure="determinar";
	var $b_empty_t="Por favor rellene el título";
	var $b_empty_content="Por favor rellene el contenido";
	var $b_his_blog="{holder}Iniciar sesión";
	var $b_re_suc="Comentarios exitosas";
	var $b_re_last="Volver a la anterior";
	var $b_face="expresión";
	var $b_pri="intimidad";
	
	var $b_content_not_saved="Su entrada no se ha guardado!";
	var $b_label="etiqueta";
	var $b_set_permissions="Permisos de acceso Set";
	var $b_data_loading="Cargando, por favor espere...";
	var $b_share="cuota";
	var $b_report="informe";	
	var $b_right_set_competence="Haga clic derecho para establecer los derechos de acceso";
	var $b_write_new_log = "Escribir un nuevo registro";
	var $b_write_new_ask = "Hacer una nueva pregunta";
	var $b_write_ask_re = "respuesta";
	var $b_write_ask_qu = "Preguntas planteadas";
	
};
?>