<?php
class mypalslp{
	var $translate_s="Utilice esta función para la devolución de cargo 1 oro más bajo";
	var $mp_mypals="círculo de los amigos";
	var $mp_list="Lista de Amigos";
	var $mp_re_list="Lista Devoluciones amigos";
	var $mp_re_search="Amigos consulta devuelve";
	var $mp_req="Amigos aplicación";
	var $mp_invite="Invitar amigo";
	var $mp_add="Añadir amigo";
	var $mp_find="Encuentra Amigos";
	var $mp_req_false="La no presentación de información de la aplicación, por favor vuelva a enviar";
	var $mp_not_self="No se puede agregar a sí mismo como un amigo";
	var $mp_rep_req="El usuario tiene la lista";
	var $mp_info_wrong="Error de la Información, por favor, verifique antes de añadir amigos";
	var $mp_suc_reg="Ha presentado una solicitud";
	var $mp_suc_add="Amigos agregado con éxito";
	var $mp_suc_del="eliminados con éxito";
	var $mp_act_suc="operación exitosa";
	var $mp_ref_add="El usuario niega petición de añadir";
	var $mp_no_pals="No son amigos,<a href='modules.php?app=mypals_search'>Encuentra Amigos</a>";
	var $mp_del_req="Eliminar una aplicación";
	var $mp_con_del_req="¿Está seguro que desea eliminar este solicitudes de amistad?";
	var $mp_def_ico="avatar predeterminado";
	var $mp_name="nombre de usuario";
	var $mp_con_tool="herramientas de comunicación";
	var $mp_mypals_state="Amigos Estado";
	var $mp_wait_confirm="La aplicación ha sido aún emitido confirmado";
	var $mp_other_confirm="Los amigos han sido confirmados";
	var $mp_both_confirm="Amigos y mutuamente reconocido";
	var $mp_a_del="¿Está seguro que desea eliminar este amigo?";
	var $mp_en_home="Entrar Home";
	var $mp_send_scrip="Enviar un pedazo pequeño de papel";
	var $mp_no_req="Usted todavía no ha recibido una solicitud,<a href='modules.php?app=mypals_search'>Encuentra Amigos</a>";
	var $mp_del="Retire amigo";
	var $mp_req_time="El tiempo de aplicación";
	var $mp_ctrl="funcionamiento";
	var $mp_req_name="Usuarios de la aplicación";
	var $mp_both_pal="Acordó atarlo a un amigo";
	var $mp_other_pal="acordar";
	var $mp_ref_pal="negativa";
	var $mp_age="siglos";
	var $mp_empty_search="La información de consulta no puede estar vacío";
	var $mp_online_search="Buscar en línea";
	var $mp_name_search="Encuentra amigos por nombre";
	var $mp_area_search="Encuentra geográfica Amigos";
	var $mp_man="masculino";
	var $mp_woman="femenino";
	var $mp_third_man="él";
	var $mp_third_woman="ella";
	var $mp_sex="sexo";
	var $mp_reside="ubicación";
	var $mp_birth="Procedencia";
	var $mp_country="país";
	var $mp_no_search="¿No has encontrado lo que busca para los usuarios,<a href='modules.php?app=mypals_search'>Nueva búsqueda</a>";
	var $mp_search_none="Lo sentimos, pero no encontró lo que está buscando para los usuarios";
	var $mp_add_mypals="más{he}Amigos";
	var $mp_scrip="a{he}Enviar un pedazo pequeño de papel";
	var $mp_unset="No establecido";
	var $mp_more="más";
	var $mp_sort="grupo de amigos";
	var $mp_m_sort="Dirección del Grupo";
	var $mp_s_sort="Seleccione el grupo";
	var $mp_no_sort="Sin grupo";
	var $mp_def_sort="predeterminado agrupación";
	var $mp_add_sort="Añadir un grupo";
	var $mp_t_sort="añadir";
	var $mp_sort_pals="No hay amigos en este grupo";
	var $mp_whole="Todos los Amigos";
	var $mp_p_sel="Por favor seleccione";
	var $mp_height="altura";
	var $mp_income="ingresos";
	var $mp_sort_wrong="Por favor, rellene el nombre de la categoría";
	var $mp_import_name="Por favor, introduzca el nombre que desea encontrar un amigo";
	var $mp_remind="{num}Amigos de aplicación";
	var $mp_none_search="Lo sentimos, no encontramos que esto un amigo";
	var $mp_select_sort="Seleccione el grupo";
	var $mp_search="búsqueda";
	var $mp_search_cond="Por favor seleccione sus criterios de búsqueda";
	var $mp_online="Online";
	var $mp_none_limit="limitación";
	
	var $mp_pal_recomment = "recomendar";
	var $mp_pal_birth = "Amigos Cumpleaños";
	var $mp_pal_nofri = "Sin amigos cumpleaños";
	var $mp_invite_more="Invita a más amigos y colegas a unirse";
	var $mp_instant_ct_link="Puede QQ, MSN y otras herramientas de mensajería instantánea, o enviar por correo electrónico, en el enlace para decirle a sus amigos, los invitamos a unirse pulg。";
	var $mp_instant_ct_send="También puede modificar o directamente haga clic en el botón 'Copy' para bajar breve de invitación por QQ, MSN o email Enviar a más amigos。";
	var $mp_brief_invitation="Corto Invitación";
	var $mp_i="我是";
	var $mp_invite_you="La creación de una página personal, que le invita a unirse y convertirse en mi amigo。";
	var $mp_contact_me="Añadir a mis amigos, usted puede aprender a través de mi página personal de mi situación, de compartir mis fotos, estar en contacto conmigo。";
	var $mp_invited_postscript="Invite posdata：";
	var $mp_links_invite="Haga clic en el enlace de abajo para recibir a un amigo Invita：";
	var $mp_if_you_have="Si usted tiene";
	var $mp_view_personal_homepage="Teniendo en cuenta, por favor haga clic en el siguiente enlace para ver mi página personal：";
	var $mp_ctrlc_start="Haga clic para copiar el contenido, los mensajes de pasta a través de QQ, MSN o correo electrónico a un amigo";
	var $mp_ctrlc_success="Copiado con éxito, Ctrl + V para pegar directamente";
	var $mp_ctrlc_failure="Su navegador no soporta la función de auto-copia, use Ctrl + C para copiar";
	var $mp_all="todo";
	var $mp_add_you="Pide que se añada como amigo";
	var $mp_years="años";
	var $mp_over="arriba";
	var $mp_province="provincia";
	var $mp_city="ciudad";
	
	var $mp_system_sends = "El sistema envía";
	var $mp_a_notice = "Un aviso";
	var $mp_treatment_success = "El éxito del tratamiento";
	var $mp_treatment_failure = "Procesamiento fallado";
	var $mp_select = "seleccionar";
	var $mp_cancel = "cancelar";
	var $mp_delete = "borrar";
	var $mp_generate_invite = "Generar código de invitación";
	var $mp_invite_cost = "Cada generación de código de invitación le costará";
	var $mp_integral = "integración";
	var $mp_surplus_integral = "Sus puntos restantes actuales para el";
	var $mp_invitation_code_period = "Nota: El código de invitación es válida para la generación de";
	var $mp_in_hours = "En cuestión de horas";
	var $mp_begin_to = "Comenzó a producir";
	var $mp_invite_code_error = "Código de invitación genera un error";
	var $mp_congratulations_invite_code = "Enhorabuena, se genera el código de invitación：";


    var $mp_all_members="Todos los miembros";
    var $mp_online_members="Online";
    var $mp_new_members="Miembros más recientes";
    var $mp_search_members="Buscar Miembros";
    var $mp_xingzuo="Horóscopo del partido";
    var $mp_online_num="Actualmente hay{online_num}Online! Online se actualiza cada cinco minutos！";

	var $mp_quanxian='Le invitamos a navegar con derecho a recargar y actualizar';
	var $mp_noyear='Edad desconocida';
	
	var $mp_success='eliminados con éxito';
	
};
?>