<?php
class bloglp{
	var $b_blog="Блог";
	var $b_mine="Мой блог";
	var $b_friend="Друзья блог";
	var $b_creat="Новый блог";
	var $b_edit="редактор";
	var $b_lock="Блог заблокирован";
	var $b_search="поиск по блогам";
	var $b_re_list="Вернуться к списку блоге";
	var $b_scan="Читать дневник";
	var $b_add_suc="Добавить блог успешного";
	var $b_add_fal="Непредставление блог, пожалуйста, повторно";
	var $b_edit_suc="Изменить успех блога!";
	var $b_edit_false="Изменить блог удалось!";
	var $b_del_suc="Удалить успех блога";
	var $b_del_false="Не удалось удалить блог!";
	var $b_no_pass="Пожалуйста, заполните все варианты";
	var $b_manage_sort="Блог классификация";
	var $b_def_sort="Категория по умолчанию (Не поддерживает редактирование и удаление)";
	var $b_del_sort_suc="Удалить успех классификации";
	var $b_change_sort_suc="Изменить успех классификации";
	var $b_change_sort_false="Не удалось изменить классификацию";
	var $b_only_fri_com="Только авторские Друзья Комментарии";
	var $b_not_com="Этот блог не комментировать";
	var $b_num="иметь{num}Статьи блог";
	var	$b_title="название";
	var $b_sort="классификация";
	var $b_author="автор";
	var $b_default_sort="Категория по умолчанию";
	var $b_com_num="комментарий({b_com_num})";
	var $b_read_num="читать({b_read_num})";
	var $b_no_fri_blog="К сожалению, нет, вы можете просмотреть текущий журнал";
	var $b_del="удалять";
	var $b_a_del="удалять?";
	var $b_button_save="экономить";
	var $b_button_cancel="отменить";
	var $b_none="Вы не добавляли журнал,<a href='modules.php?app=blog_edit'>Создайте журнал</a>,или<a href='modules.php?app=blog_friend'>Журнал Просмотреть Друзья</a>";
	var $b_limit="компетентность";
	var $b_same_sort="Проверьте с классификацией блоге";
	var $b_public="общественный";
	var $b_private="только самостоятельно";
	var $b_pals="только Друзья";
	var $b_error="Информация, которую вы посетите страницу не существует";
	var $b_empty="Пожалуйста, заполните информацию";
	var $b_limit_blog="Так как множество журнала разрешений, вы не можете получить доступ к";
	var $b_they_com="Отзывы пользователей";
	var $b_send_time="Написано в:{date_time}";
	var $b_i_com="Написано в";
	var $b_button_re="ответ";
	var $b_button_clear="удалять";
	var $b_add_sort="Добавить категории";
	var $b_content="содержание";
	var $b_pic="картинка";
	var $b_sel_album="（Выберите Загрузить изображение непосредственно с альбома）";
	var $b_button_sure="определять";
	var $b_empty_t="Пожалуйста, заполните в названии";
	var $b_empty_content="Пожалуйста, заполните содержания";
	var $b_his_blog="{holder}Блог";
	var $b_re_suc="Комментарии успешные";
	var $b_re_last="Вернуться к предыдущему";
	var $b_face="выражение";
	var $b_pri="конфиденциальность";
	
	var $b_content_not_saved="Ваш вклад не был сохранен!";
	var $b_label="тег";
	var $b_set_permissions="Установите права доступа доступа";
	var $b_data_loading="Загрузка, пожалуйста, подождите...";
	var $b_share="доля";
	var $b_report="отчет";	
	var $b_right_set_competence="Щелкните правой кнопкой мыши, чтобы установить права доступа";
	var $b_write_new_log = "Написал новый блог";
	var $b_write_new_ask = "Задать вопрос";
	var $b_write_ask_re = "ответ";
	var $b_write_ask_qu = "Вопросы, поднятые";
	
};
?>