<?php
class mypalslp{
	var $translate_s="Используйте эту функцию для самой низкой платежа 1 золота";
	var $mp_mypals="Круг друзей";
	var $mp_list="Друзья Список";
	var $mp_re_list="Возвращает список друзей";
	var $mp_re_search="Друзья запрос возвращает";
	var $mp_req="приложение Друзья";
	var $mp_invite="Друг Пригласить";
	var $mp_add="Добавить в друзья";
	var $mp_find="Поиск друзей";
	var $mp_req_false="Непредставление информации о приложении, пожалуйста, повторно";
	var $mp_not_self="Не можете добавить себя в список знакомых";
	var $mp_rep_req="Пользователь имеет список";
	var $mp_info_wrong="Информация об ошибке, пожалуйста, проверьте, прежде чем добавлять друзей";
	var $mp_suc_reg="Подал заявку";
	var $mp_suc_add="Друзья успешно добавлен";
	var $mp_suc_del="Удаленные успешно";
	var $mp_act_suc="Успешная работа";
	var $mp_ref_add="Пользователь отрицает запрос на добавление";
	var $mp_no_pals="Вы не друзья,<a href='modules.php?app=mypals_search'>Поиск друзей</a>";
	var $mp_del_req="Удаление приложения";
	var $mp_con_del_req="Вы уверены, что хотите удалить этот друг запросы?";
	var $mp_def_ico="По умолчанию Аватара";
	var $mp_name="имя пользователя";
	var $mp_con_tool="средства коммуникации";
	var $mp_mypals_state="Друзья Статус";
	var $mp_wait_confirm="Заявка была выдана еще подтвердил";
	var $mp_other_confirm="Друзья были подтверждены";
	var $mp_both_confirm="Друзья и взаимно признаются";
	var $mp_a_del="Вы уверены, что хотите удалить этот друга?";
	var $mp_en_home="Введите Главная";
	var $mp_send_scrip="Отправить небольшой листок бумаги";
	var $mp_no_req="Вы еще не получил заявку,<a href='modules.php?app=mypals_search'>Поиск друзей</a>";
	var $mp_del="Удалить друзья";
	var $mp_req_time="время применения";
	var $mp_ctrl="рабочий";
	var $mp_req_name="Применение Пользователи";
	var $mp_both_pal="Согласен, чтобы связать его другу";
	var $mp_other_pal="соглашаться";
	var $mp_ref_pal="отказ";
	var $mp_age="века";
	var $mp_empty_search="Информация Запрос не может быть пустым";
	var $mp_online_search="Найти на сайте";
	var $mp_name_search="Найти друзей по имени";
	var $mp_area_search="Географическое найти друзей";
	var $mp_man="мужской";
	var $mp_woman="женский";
	var $mp_third_man="он";
	var $mp_third_woman="она";
	var $mp_sex="Пол";
	var $mp_reside="расположение";
	var $mp_birth="Родной город";
	var $mp_country="страна";
	var $mp_no_search="Не нашли то, что вы ищете пользователей,<a href='modules.php?app=mypals_search'>Новый поиск</a>";
	var $mp_search_none="К сожалению, не найти то, что вы ищете для пользователей";
	var $mp_add_mypals="плюс{he}Друзья";
	var $mp_scrip="к{he}Отправить небольшой листок бумаги";
	var $mp_unset="Не установлено";
	var $mp_more="более";
	var $mp_sort="группа Друзья";
	var $mp_m_sort="руппа управления";
	var $mp_s_sort="Выбор группы";
	var $mp_no_sort="разгруппирована";
	var $mp_def_sort="По умолчанию группировка";
	var $mp_add_sort="Добавить группу";
	var $mp_t_sort="добавлять";
	var $mp_sort_pals="Нет друзей в этой группе";
	var $mp_whole="Все друзья";
	var $mp_p_sel="Пожалуйста, выберите";
	var $mp_height="высота";
	var $mp_income="доход";
	var $mp_sort_wrong="Пожалуйста, заполните имя категории";
	var $mp_import_name="Пожалуйста, введите имя, которое вы хотите найти друга";
	var $mp_remind="{num}Друзья по применению";
	var $mp_none_search="К сожалению, не считали это другу";
	var $mp_select_sort="Выбор группы";
	var $mp_search="поиск";
	var $mp_search_cond="Пожалуйста, выберите критерии поиска";
	var $mp_online="онлайн";
	var $mp_none_limit="ограничение";
	
	var $mp_pal_recomment = "рекомендовать";
	var $mp_pal_birth = "Друзья День рождения";
	var $mp_pal_nofri = "Нет друзей день рождения";
	var $mp_invite_more="Пригласи еще друзей и коллег присоединиться";
	var $mp_instant_ct_link="Вы можете QQ, MSN и другие инструменты IM, или отправить по электронной почте, на ссылку ниже, чтобы рассказать своим друзьям, пригласить их присоединиться к дюйма.";
	var $mp_instant_ct_send="Вы также можете изменить или просто нажать кнопку Копировать, чтобы снизить короткий приглашение на QQ, MSN или по электронной почте отправить больше друзей.";
	var $mp_brief_invitation="Короткие Приглашение";
	var $mp_i="Я был";
	var $mp_invite_you="Основанная личную страницу, приглашаем вас присоединиться и стать своего друга.";
	var $mp_contact_me="Добавь в друзья, вы можете узнать через мой личный домашней странице моей ситуации, чтобы поделиться своими фотографиями, поддерживать связь со мной.";
	var $mp_invited_postscript="Пригласить постскриптум：";
	var $mp_links_invite="Нажмите на ссылку ниже, чтобы получить друг пригласить：";
	var $mp_if_you_have="Если у вас есть";
	var $mp_view_personal_homepage="На счету, пожалуйста, нажмите на следующую ссылку, чтобы увидеть мою личную страницу：";
	var $mp_ctrlc_start="Нажмите, чтобы скопировать содержимое, вставки сообщения через QQ, MSN или Отправить другу";
	var $mp_ctrlc_success="Скопировано успешно, Ctrl + V, чтобы вставить непосредственно";
	var $mp_ctrlc_failure="Ваш браузер не поддерживает функцию автоматического копирования, используйте Ctrl + C, чтобы скопировать";
	var $mp_all="весь";
	var $mp_add_you="Просьба добавить вас в друзья";
	var $mp_years="оды";
	var $mp_over="выше";
	var $mp_province="провинция";
	var $mp_city="Сити";
	
	var $mp_system_sends = "система отправляет";
	var $mp_a_notice = "уведомление";
	var $mp_treatment_success = "успех лечения";
	var $mp_treatment_failure = "Обработка не удалось";
	var $mp_select = "выбирать";
	var $mp_cancel = "отменить";
	var $mp_delete = "удалять";
	var $mp_generate_invite = "Создать код приглашения";
	var $mp_invite_cost = "Каждое поколение код приглашения будет стоить вам";
	var $mp_integral = "интеграция";
	var $mp_surplus_integral = "Текущего кол-ва очков за";
	var $mp_invitation_code_period = "Примечание: Код Приглашение действительно для генерации";
	var $mp_in_hours = "В течение нескольких часов";
	var $mp_begin_to = "начали производить";
	var $mp_invite_code_error = "Приглашение код генерирует ошибку";
	var $mp_congratulations_invite_code = "Поздравляем, ваш код приглашения генерируется：";


    var $mp_all_members="Все Пользователи";
    var $mp_online_members="онлайн";
    var $mp_new_members="Новые члены";
    var $mp_search_members="Поиск Пользователи";
    var $mp_xingzuo="星座速配";
    var $mp_online_num="Есть в настоящее время{online_num}онлайн！在线会员每5分钟更新一次！";

	var $mp_quanxian='Пожалуйста, просмотрите право пополнить счет и модернизировать';
	var $mp_noyear='Возраст неизвестен';
	
	var $mp_success='Удаленные успешно';
	
};
?>