<?php
class bloglp{
	var $b_blog="Blog";
	var $b_mine="My blog";
	var $b_friend="Friends blog";
	var $b_creat="New blog";
	var $b_edit="Editor";
	var $b_lock="The blog has been locked";
	var $b_search="Blog search";
	var $b_re_list="Return to blog list";
	var $b_scan="Read blog";
	var $b_add_suc="Submit a blog successful";
	var $b_add_fal="Failure to submit blog,Please resubmit";
	var $b_edit_suc="Modify blog success!";
	var $b_edit_false="Modify blog Failed!";
	var $b_del_suc="Delete blog success";
	var $b_del_false="Failed to delete blog!";
	var $b_no_pass="Please fill each option";
	var $b_manage_sort="Blog classification";
	var $b_def_sort="Default Category (Does not support editing and deleting)";
	var $b_del_sort_suc="Delete classification success";
	var $b_change_sort_suc="Modify the classification success";
	var $b_change_sort_false="Failed to modify the classification";
	var $b_only_fri_com="Only the author's Friends Comments";
	var $b_not_com="This log can not comment";
	var $b_num="Have{num}blog";
	var	$b_title="Title";
	var $b_sort="Classification";
	var $b_author="Author";
	var $b_default_sort="Default Category";
	var $b_com_num="Comment({b_com_num})";
	var $b_read_num="Read({b_read_num})";
	var $b_no_fri_blog="Sorry, currently there is no you can view blog";
	var $b_del="Delete";
	var $b_a_del="Delete?";
	var $b_button_save="Save";
	var $b_button_cancel="Cancel";
	var $b_none="You have not added blog,<a href='modules.php?app=blog_edit'>Create a blog</a>,Or<a href='modules.php?app=blog_friend'>Browse friend's blog</a>";
	var $b_limit="Competence";
	var $b_same_sort="Check with the classification of blog";
	var $b_public="Public";
	var $b_private="Only their own";
	var $b_pals="Friends only";
	var $b_error="Information you visit the page does not exist";
	var $b_empty="Please fill out the information";
	var $b_limit_blog="Since the log set permissions, you can not access";
	var $b_they_com="User Reviews";
	var $b_send_time="Published in:{date_time}";
	var $b_i_com="I want to comment";
	var $b_button_re="Reply";
	var $b_button_clear="Remove";
	var $b_add_sort="Add categories";
	var $b_content="Content";
	var $b_pic="Picture";
	var $b_sel_album="（Select Image uploaded directly from the album）";
	var $b_button_sure="Determine";
	var $b_empty_t="Please fill in the title";
	var $b_empty_content="Please fill in the content";
	var $b_his_blog="{holder}blog";
	var $b_re_suc="Comments successful";
	var $b_re_last="Return to the previous one";
	var $b_face="Expression";
	var $b_pri="Privacy";
	
	var $b_content_not_saved="Your input has not been saved!";
	var $b_label="Tag";
	var $b_set_permissions="Set access permissions";
	var $b_data_loading="Data loading, please wait...";
	var $b_share="Share";
	var $b_report="Report";	
	var $b_right_set_competence="Right click to set access rights";
	var $b_write_new_log = "Write a new log";
	var $b_write_new_ask = "Ask a new question";
	var $b_write_ask_re = "Answer";
	var $b_write_ask_qu = "Questions raised";
	
};
?>