<?php
class mypalslp{
	var $translate_s="Use this function minimum deduction 1 gold COINS";
	var $mp_mypals="Circle of friends";
	var $mp_list="Friends list";
	var $mp_re_list="Returns friends list";
	var $mp_re_search="Friends query returns";
	var $mp_req="Friend requests";
	var $mp_invite="Friend request";
	var $mp_add="Add Friend";
	var $mp_find="Find Friends";
	var $mp_req_false="Failure to submit application information, please resubmit";
	var $mp_not_self="Can not add yourself as a friend";
	var $mp_rep_req="The user has the list";
	var $mp_info_wrong="Wrong information, please check again after add buddy";
	var $mp_suc_reg="Has submitted an application";
	var $mp_suc_add="Friends added successfully";
	var $mp_suc_del="Deleted successfully";
	var $mp_act_suc="Successful operation";
	var $mp_ref_add="The user denies request to add";
	var $mp_no_pals="You are not friends,<a href='modules.php?app=mypals_search'>Find Friends</a>";
	var $mp_del_req="Delete an application";
	var $mp_con_del_req="Are you sure you want to delete this friend requests?";
	var $mp_def_ico="Default avatar";
	var $mp_name="User name";
	var $mp_con_tool="Communication tools";
	var $mp_mypals_state="Friends Status";
	var $mp_wait_confirm="Notice of the application has not been confirmed";
	var $mp_other_confirm="Friends have been confirmed";
	var $mp_both_confirm="Friends and mutually recognized";
	var $mp_a_del="Are you sure you want to delete this friend?";
	var $mp_en_home="Enter the home page";
	var $mp_send_scrip="Send a small piece of paper";
	var $mp_no_req="You have not yet received an application,<a href='modules.php?app=mypals_search'>Find Friends</a>";
	var $mp_del="Remove Friend";
	var $mp_req_time="Request Time";
	var $mp_ctrl="Operating";
	var $mp_req_name="To apply for the user";
	var $mp_both_pal="Tied for the agreed as a friend";
	var $mp_other_pal="Agree";
	var $mp_ref_pal="Refusal";
	var $mp_age="Ages";
	var $mp_empty_search="Query information can not be empty";
	var $mp_online_search="Find Online";
	var $mp_name_search="According to the name to find friends";
	var $mp_area_search="According to the region to find friends";
	var $mp_man="Male";
	var $mp_woman="Female";
	var $mp_third_man="He";
	var $mp_third_woman="She";
	var $mp_sex="Gender";
	var $mp_reside="Location";
	var $mp_birth="Hometown";
	var $mp_country="Country";
	var $mp_no_search="Did not find what you're looking for users,<a href='modules.php?app=mypals_search'>New Search</a>";
	var $mp_search_none="Sorry, did not find what you're looking for users";
	var $mp_add_mypals="Plus {he} as a friend";
	var $mp_scrip="To {he} Send a small piece of paper";
	var $mp_unset="Not set";
	var $mp_more="More";
	var $mp_sort="Friends group";
	var $mp_m_sort="Group Management";
	var $mp_s_sort="Select group";
	var $mp_no_sort="Ungrouped";
	var $mp_def_sort="Default grouping";
	var $mp_add_sort="Add a group";
	var $mp_t_sort="Add";
	var $mp_sort_pals="No friends in this group";
	var $mp_whole="All Friends";
	var $mp_p_sel="Please select";
	var $mp_height="Height";
	var $mp_income="Income";
	var $mp_sort_wrong="Please fill out the category name";
	var $mp_import_name="Please enter the name you want to find a friend";
	var $mp_remind="{num}Friend Request";
	var $mp_none_search="Sorry, did not find this a friend";
	var $mp_select_sort="Select group";
	var $mp_search="Search";
	var $mp_search_cond="Please select your search criteria";
	var $mp_online="Online";
	var $mp_none_limit="Unlimited";
	
	var $mp_pal_recomment = "Recommend";
	var $mp_pal_birth = "Friends Birthday";
	var $mp_pal_nofri = "No friends birthday";
	var $mp_invite_more="Invite more friends and colleagues to join";
	var $mp_instant_ct_link="You can QQ, MSN and other IM tools, or send e-mail, the link below to tell your friends, invite them to join in.";
	var $mp_instant_ct_send="You can also modify or directly click the 'Copy' button to lower short invitation by QQ, MSN or Email send to more friends.";
	var $mp_brief_invitation="Short Invitation";
	var $mp_i="I am";
	var $mp_invite_you="Established a personal home page, inviting you to join and become my friend.";
	var $mp_contact_me="Add to my friends, you can learn through my personal home page of my situation, to share my photos, keep in touch with me.";
	var $mp_invited_postscript="Invite postscript：";
	var $mp_links_invite="Click the link below to receive a friend invite：";
	var $mp_if_you_have="If you have";
	var $mp_view_personal_homepage="On account, please click on the following link to see my personal home page：";
	var $mp_ctrlc_start="Click to copy the contents, paste messages through QQ, MSN or Email to a Friend";
	var $mp_ctrlc_success="Copied successfully, Ctrl + V to paste directly";
	var $mp_ctrlc_failure="Your browser does not support auto-copy function, use Ctrl + C to copy";
	var $mp_all="All";
	var $mp_add_you="Request to add you as a friend";
	var $mp_years="Age";
	var $mp_over="Above";
	var $mp_province="Province";
	var $mp_city="City";
	
	var $mp_system_sends = "System sends";
	var $mp_a_notice = "Notice";
	var $mp_treatment_success = "Handle a successful";
	var $mp_treatment_failure = "To deal with failure";
	var $mp_select = "Select";
	var $mp_cancel = "Cancel";
	var $mp_delete = "Delete";
	var $mp_generate_invite = "Generate invitation code";
	var $mp_invite_cost = "Every invitation code generation will cost you";
	var $mp_integral = "points";
	var $mp_surplus_integral = "Your current remaining points for the";
	var $mp_invitation_code_period = "Note: The invitation code is valid for";
	var $mp_in_hours = "Within hours";
	var $mp_begin_to = "Began to produce";
	var $mp_invite_code_error = "Invitation code generates an error";
	var $mp_congratulations_invite_code = "Congratulations, your invitation code is generated：";


    var $mp_all_members="全部会员";
    var $mp_online_members="在线会员";
    var $mp_new_members="最新会员";
    var $mp_search_members="搜索会员";
    var $mp_xingzuo="星座速配";
    var $mp_online_num="目前共有{online_num}人在线！在线会员每5分钟更新一次！";

	var $mp_quanxian='无权浏览 请充值和升级';
	var $mp_noyear='年龄未知';
	
	var $mp_success='删除成功';
	
};
?>