<?php
class bloglp{
	var $b_blog="日誌";
	var $b_mine="我的日誌";
	var $b_friend="好友日誌";
	var $b_creat="新建日誌";
	var $b_edit="編輯";
	var $b_lock="該日誌已經被鎖定";
	var $b_search="日誌搜索";
	var $b_re_list="返回日誌列表";
	var $b_scan="瀏覽日誌";
	var $b_add_suc="提交日誌成功";
	var $b_add_fal="提交日誌失敗,請重新提交";
	var $b_edit_suc="修改日誌成功!";
	var $b_edit_false="修改日誌失敗!";
	var $b_del_suc="刪除日誌成功";
	var $b_del_false="刪除日誌失敗!";
	var $b_no_pass="請認真填寫每個選項";
	var $b_manage_sort="日誌分類";
	var $b_def_sort="默認分類 (不支持編輯及刪除)";
	var $b_del_sort_suc="刪除分類成功";
	var $b_change_sort_suc="修改分類成功";
	var $b_change_sort_false="修改分類失敗";
	var $b_only_fri_com="僅能作者的好友評論";
	var $b_not_com="此日誌不能進行評論";
	var $b_num="有{num}篇日誌";
	var	$b_title="標題";
	var $b_sort="分類";
	var $b_author="作者";
	var $b_default_sort="默認分類";
	var $b_com_num="評論({b_com_num})";
	var $b_read_num="閱讀({b_read_num})";
	var $b_no_fri_blog="對不起，當前沒有您可以查看的日誌";
	var $b_del="刪除";
	var $b_a_del="是否刪除?";
	var $b_button_save="保存";
	var $b_button_cancel="取消";
	var $b_none="您還沒有添加日誌,<a href='modules.php?app=blog_edit'>創建日誌</a>,或者<a href='modules.php?app=blog_friend'>瀏覽好友的日誌</a>";
	var $b_limit="權限";
	var $b_same_sort="查看同分類的日誌";
	var $b_public="公開";
	var $b_private="僅自己";
	var $b_pals="僅好友";
	var $b_error="您訪問的頁面信息不存在";
	var $b_empty="請填寫信息";
	var $b_limit_blog="猶豫該日誌設置了權限，您無法訪問";
	var $b_they_com="網友評論";
	var $b_send_time="發表於:{date_time}";
	var $b_i_com="我要評論";
	var $b_button_re="評論";
	var $b_button_clear="清除";
	var $b_add_sort="添加分類";
	var $b_content="內容";
	var $b_pic="圖片";
	var $b_sel_album="（直接從相冊中選擇圖片上傳）";
	var $b_button_sure="確定";
	var $b_empty_t="請填寫標題";
	var $b_empty_content="請填寫內容";
	var $b_his_blog="{holder}的日誌";
	var $b_re_suc="評論成功";
	var $b_re_last="返回上一級";
	var $b_face="表情";
	var $b_pri="隱私";
	
	var $b_content_not_saved="您填寫的內容尚未保存!";
	var $b_label="標籤";
	var $b_set_permissions="設置訪問權限";
	var $b_data_loading="數據加載中,請稍候...";
	var $b_share="分享";
	var $b_report="舉報";	
	var $b_right_set_competence="點擊右鍵設置訪問權限";
	var $b_write_new_log = "寫了心日誌";
	var $b_write_new_ask = "提出新問題";
	var $b_write_ask_re = "回答";
	var $b_write_ask_qu = "提出的問題";
	
};
?>