<?php
class mypalslp{
var $translate_s="使用此功能最低扣費1金幣";
	var $mp_mypals="朋友圈";
	var $mp_list="好友列表";
	var $mp_re_list="返回好友列表";
	var $mp_re_search="返回好友查詢";
	var $mp_req="好友申請";
	var $mp_invite="好友邀請";
	var $mp_add="添加好友";
	var $mp_find="查找好友";
	var $mp_req_false="提交申請信息失敗,請重新提交";
	var $mp_not_self="不能加自己為好友";
	var $mp_rep_req="該用戶已在列表中";
	var $mp_info_wrong="信息錯誤,請查證後在添加好友";
	var $mp_suc_reg="已提交申請";
	var $mp_suc_add="好友添加成功";
	var $mp_suc_del="刪除成功";
	var $mp_act_suc="操作成功";
	var $mp_ref_add="該用戶拒絕添加請求";
	var $mp_no_pals="您還沒有好友,<a href='modules.php?app=mypals_search'>查找好友</a>";
	var $mp_del_req="刪除申請";
	var $mp_con_del_req="您確定要刪除此好友申請?";
	var $mp_def_ico="默認頭像";
	var $mp_name="用戶名";
	var $mp_con_tool="交流工具";
	var $mp_mypals_state="好友狀態";
	var $mp_wait_confirm="已發出申請尚未確認";
	var $mp_other_confirm="已獲取好友";
	var $mp_both_confirm="已確認并互為好友";
	var $mp_a_del="您確定要刪除這個好友?";
	var $mp_en_home="進入首頁";
	var $mp_send_scrip="發送小紙條";
	var $mp_no_req="您還沒有收到申請,<a href='modules.php?app=mypals_search'>查找好友</a>";
	var $mp_del="刪除好友";
	var $mp_req_time="申請時間";
	var $mp_ctrl="操作";
	var $mp_req_name="申請用戶";
	var $mp_both_pal="同意並列其為好友";
	var $mp_other_pal="同意";
	var $mp_ref_pal="拒絕";
	var $mp_age="年齡段";
	var $mp_empty_search="查詢信息不能為空";
	var $mp_online_search="在綫查找";
	var $mp_name_search="按姓名查找好友";
	var $mp_area_search="按地域查找好友";
	var $mp_man="男";
	var $mp_woman="女";
	var $mp_third_man="他";
	var $mp_third_woman="她";
	var $mp_sex="性别";
	var $mp_reside="所在地";
	var $mp_birth="家鄉";
	var $mp_country="國家";
	var $mp_no_search="沒有找到您要查找的用戶,<a href='modules.php?app=mypals_search'>重新搜索</a>";
	var $mp_search_none="對不起，沒有找到您要查找的用户";
	var $mp_add_mypals="加{he}為好友";
	var $mp_scrip="给{he}發送小紙條";
	var $mp_unset="未設置";
	var $mp_more="更多";
	var $mp_sort="好友分組";
	var $mp_m_sort="分组管理";
	var $mp_s_sort="選擇分组";
	var $mp_no_sort="未分组";
	var $mp_def_sort="默認分组";
	var $mp_add_sort="添加分组";
	var $mp_t_sort="添加";
	var $mp_sort_pals="这个分组里還沒好友";
	var $mp_whole="全部好友";
	var $mp_p_sel="請選擇";
	var $mp_height="身高";
	var $mp_income="收入";
	var $mp_sort_wrong="請填寫分類名稱";
	var $mp_import_name="請輸入你要查找好友的名字";
	var $mp_remind="{num}个好友申請";
	var $mp_none_search="對不起，沒有找到此好友";
	var $mp_select_sort="選擇分組";
	var $mp_search="搜索";
	var $mp_search_cond="您選擇您的搜索條件";
	var $mp_online="在綫";
	var $mp_none_limit="不限";
	
	var $mp_pal_recomment = "推薦";
	var $mp_pal_birth = "好友生日";
	var $mp_pal_nofri = "沒有好友過生日";
	var $mp_invite_more="邀請更多的朋友和同時加入";
	var $mp_instant_ct_link="您可以通過QQ、MSN等IM工具，或者發送郵件，把下面的連接告訴你的好友，邀請他們加入進來。";
	var $mp_instant_ct_send="您還可以修改或直接點擊“複製”按鈕，將下邊的簡短邀請函通過QQ、MSN或Email發送給更多好友。";
	var $mp_brief_invitation="簡短邀請函";
	var $mp_i="我是";
	var $mp_invite_you="上建立了個人主頁，要請你也加入並成為我的好友。";
	var $mp_contact_me="加入到我的好友中，你就可以通過我的個人主頁瞭解我的近況，分享我的照片，隨時與我保持聯繫。";
	var $mp_invited_postscript="邀請附言：";
	var $mp_links_invite="點擊以下鏈接，接受好友邀请：";
	var $mp_if_you_have="如果你擁有";
	var $mp_view_personal_homepage="上的帳號，請點擊以下連接查看我的個人主頁：";
	var $mp_ctrlc_start="點擊複製內容，粘貼消息通過QQ、MSN或Email發送給好友";
	var $mp_ctrlc_success="複製成功,直接Ctrl+V進行粘貼";
	var $mp_ctrlc_failure="您的瀏覽器不支持自動複製功能，請使用Ctrl+C進行複製";
	var $mp_all="全部";
	var $mp_add_you="請求加你為好友";
	var $mp_years="歲";
	var $mp_over="以上";
	var $mp_province="省份";
	var $mp_city="城市";
	
	var $mp_system_sends = "系統發送";
	var $mp_a_notice = "个通知";
	var $mp_treatment_success = "處理成功";
	var $mp_treatment_failure = "處理失敗";
	var $mp_select = "選擇";
	var $mp_cancel = "取消";
	var $mp_delete = "刪除";
	var $mp_generate_invite = "產生邀請碼";
	var $mp_invite_cost = "每次邀請碼的產生都會花費您";
	var $mp_integral = "積分";
	var $mp_surplus_integral = "您當前剩餘積分為";
	var $mp_invitation_code_period = "注：邀請碼的有效期為生成後的";
	var $mp_in_hours = "小時內";
	var $mp_begin_to = "開始產生";
	var $mp_invite_code_error = "邀請碼生成錯誤";
	var $mp_congratulations_invite_code = "恭喜您，您所生成的邀請碼是：";


    var $mp_all_members="全部會員";
    var $mp_online_members="在線會員";
    var $mp_new_members="最新會員";
    var $mp_search_members="搜索會員";
    var $mp_xingzuo="星座速配";
    var $mp_online_num="目前共有{online_num}人在綫，在綫會員每5分鐘更新一次！";

	var $mp_quanxian='無權瀏覽 請充值和升級';
	var $mp_noyear='年齡未知';
	
	var $mp_success='刪除成功';
	
};
?>