<?php
class bloglp{
	var $b_blog="ブログ";
	var $b_mine="私のブログ";
	var $b_friend="友達のブログ";
	var $b_creat="新しいブログ";
	var $b_edit="エディタ";
	var $b_lock="ブログはロックされている";
	var $b_search="ブログ検索";
	var $b_re_list="ブログに戻るリスト";
	var $b_scan="ブログを読む";
	var $b_add_suc="成功のブログを提出する";
	var $b_add_fal="ブログを提出しなかった場合、再送信してください";
	var $b_edit_suc="ブログの成功を修正!";
	var $b_edit_false="失敗したブログを修正!";
	var $b_del_suc="ブログの成功を削除";
	var $b_del_false="ブログの削除に失敗しました!";
	var $b_no_pass="各オプションを埋める";
	var $b_manage_sort="ブログの分類";
	var $b_def_sort="DEFAULTカテゴリ (編集・削除を支持していない)";
	var $b_del_sort_suc="削除分類するのに成功した";
	var $b_change_sort_suc="改正分類するのに成功した";
	var $b_change_sort_false="改正分類失敗";
	var $b_only_fri_com="著者の亲友だけでコメントを発表した";
	var $b_not_com="このブログはコメントをされていません";
	var $b_num="が{num}ブログ";
	var	$b_title="タイトル";
	var $b_sort="分類";
	var $b_author="著者";
	var $b_default_sort="DEFAULTカテゴリ";
	var $b_com_num="コメント({b_com_num})";
	var $b_read_num="読む({b_read_num})";
	var $b_no_fri_blog="申し訳ございませんが、当面のなかった日誌ご確認できる ";
	var $b_del="削除";
	var $b_a_del="が削除されるか";
	var $b_button_save="保存";
	var $b_button_cancel="キャンセル";
	var $b_none="あなたはまだ添加ブログ,<a href='modules.php?app=blog_edit'>ブログを作成</a>,または<a href='modules.php?app=blog_friend'>閲覧亲友のブログより</a>";
	var $b_limit="能力";
	var $b_same_sort="同分類の区別を調べてみた";
	var $b_public="公共";
	var $b_private="唯一の独自の";
	var $b_pals="友達のみ";
	var $b_error="あなたがページにアクセスした情報は存在しません";
	var $b_empty="の情報を入力してください。";
	var $b_limit_blog="同日誌に設置された権限を訪問しておりません";
	var $b_they_com="ユーザーレビュー";
	var $b_send_time="に掲載:{date_time}";
	var $b_i_com="私はコメントしたい";
	var $b_button_re="返信";
	var $b_button_clear="削除する";
	var $b_add_sort="カテゴリを追加";
	var $b_content="コンテンツ";
	var $b_pic="写真";
	var $b_sel_album="（アルバムの中からから直接写真を掲載した）";
	var $b_button_sure="決定する";
	var $b_empty_t="记入してくださいタイトル";
	var $b_empty_content="记入してください内容";
	var $b_his_blog="{holder}ブログ";
	var $b_re_suc="成功のコメント";
	var $b_re_last="上一级试験に戻ってきて";
	var $b_face="表現";
	var $b_pri="プライバシー";
	
	var $b_content_not_saved="ご記入した内容を保管していない!";
	var $b_label="タグ";
	var $b_set_permissions="訪問権限が設置され";
	var $b_data_loading="データのパイロットで、少しください侯...";
	var $b_share="分かち合い";
	var $b_report="通報";	
	var $b_right_set_competence="右ボタンをクリックして訪問が設置された権限だ」とし、";
	var $b_write_new_log = "写了新ブログ";
	var $b_write_new_ask = "新たな問題";
	var $b_write_ask_re = "答え";
	var $b_write_ask_qu = "問題提起";
	
};
?>