<?php
class mypalslp{
	var $translate_s="最低チャージ1の金には、この機能を使用し";
	var $mp_mypals="友達の輪";
	var $mp_list="フレンドリスト";
	var $mp_re_list="返しフレンドリスト";
	var $mp_re_search="友達のクエリが返す";
	var $mp_req="友達アプリケーション";
	var $mp_invite="友人が招待";
	var $mp_add="友達を追加";
	var $mp_find="友達を探す";
	var $mp_req_false="アプリケーション情報を提出しなかった場合、再送信してください";
	var $mp_not_self="友人として自分自身を追加することはできません";
	var $mp_rep_req="ユーザーがリストを持っています";
	var $mp_info_wrong="情報誤り、友人を追加する前に確認してください";
	var $mp_suc_reg="申請書を提出しました";
	var $mp_suc_add="友達の追加に成功しました";
	var $mp_suc_del="正常に削除";
	var $mp_act_suc="成功した操作";
	var $mp_ref_add="ユーザーが追加する要求を拒否し";
	var $mp_no_pals="あなたが友人ではありません,<a href='modules.php?app=mypals_search'>友達を探す</a>";
	var $mp_del_req="アプリケーションを削除する";
	var $mp_con_del_req="あなたは、この友達のリクエストを削除してもよろしいです?";
	var $mp_def_ico="デフォルトのアバター";
	var $mp_name="ユーザー名";
	var $mp_con_tool="コミュニケーションツール";
	var $mp_mypals_state="友達の状況";
	var $mp_wait_confirm="アプリケーションが発行され、まだ確認されている";
	var $mp_other_confirm="友人が確認されている";
	var $mp_both_confirm="友人との相互認識";
	var $mp_a_del="あなたは、この友人を削除してもよろしいです?";
	var $mp_en_home="ホームを入力してください";
	var $mp_send_scrip="紙の小片を送信";
	var $mp_no_req="あなたはまだアプリケーションを受け取っていません,<a href='modules.php?app=mypals_search'>友達を探す</a>";
	var $mp_del="友達を削除";
	var $mp_req_time="アプリケーション時間";
	var $mp_ctrl="オペレーティング";
	var $mp_req_name="アプリケーションユーザー";
	var $mp_both_pal="友人にそれを結ぶことに合意した";
	var $mp_other_pal="同意する";
	var $mp_ref_pal="拒否";
	var $mp_age="年齢";
	var $mp_empty_search="クエリ情報は、空にすることはできません";
	var $mp_online_search="オンラインで見つける";
	var $mp_name_search="名前で友達を見つける";
	var $mp_area_search="地理的検索友達";
	var $mp_man="男";
	var $mp_woman="女";
	var $mp_third_man="彼";
	var $mp_third_woman="彼女";
	var $mp_sex="性别";
	var $mp_reside="場所";
	var $mp_birth="故郷";
	var $mp_country="国";
	var $mp_no_search="あなたがユーザーのために探しているものを見つけることができませんでした,<a href='modules.php?app=mypals_search'>新しい検索</a>";
	var $mp_search_none="申し訳ありませんが、あなたがユーザーのために探しているものを見つけることができませんでした";
	var $mp_add_mypals="{he}友達に加える";
	var $mp_scrip="{he}紙の小片を送信";
	var $mp_unset="設定されていません";
	var $mp_more="もっと";
	var $mp_sort="フレンズ·グループ";
	var $mp_m_sort="集団経営";
	var $mp_s_sort="選択グループ";
	var $mp_no_sort="グループ化されていない";
	var $mp_def_sort="デフォルトのグループ化";
	var $mp_add_sort="グループを追加";
	var $mp_t_sort="加える";
	var $mp_sort_pals="このグループには友人ません";
	var $mp_whole="すべての友達";
	var $mp_p_sel="選択してください";
	var $mp_height="高さ";
	var $mp_income="収入";
	var $mp_sort_wrong="カテゴリ名を記入してください";
	var $mp_import_name="あなたは友人を見つけたい名前を入力してください";
	var $mp_remind="{num}友達リクエスト";
	var $mp_none_search="申し訳ありませんが、この友人を見つけられませんでした";
	var $mp_select_sort="選択グループ";
	var $mp_search="検索";
	var $mp_search_cond="検索条件を選択してください";
	var $mp_online="オンライン";
	var $mp_none_limit="無制限の";
	
	var $mp_pal_recomment = "推奨する";
	var $mp_pal_birth = "友達の誕生日";
	var $mp_pal_nofri = "友人なし誕生日ない";
	var $mp_invite_more="参加するより多くの友人や同僚を招待";
	var $mp_instant_ct_link="あなたは、QQ、MSNおよび他のIMツールか、またはあなたの友人に伝えるため、電子メールは、以下のリンクを送って参加するためにそれらを招待。";
	var $mp_instant_ct_send="また、より多くの友人に送信、変更、または直接のQQ、MSNや電子メールでの短い招待を低下させるために「コピー」ボタンをクリックすることができます。";
	var $mp_brief_invitation="招待状";
	var $mp_i="私がいた";
	var $mp_invite_you="参加し、私の友人になるためにあなたを招待し、個人用のホーム·ページを確立。";
	var $mp_contact_me="私の友達に追加、あなたは私と連絡を取り合う、私の写真を共有するために、私の状況の私の個人的なホームページを通して学ぶことができます。";
	var $mp_invited_postscript="ポストスクリプトを招待：";
	var $mp_links_invite="招待友人を受け取るには、以下のリンクをクリックしてください：";
	var $mp_if_you_have="あなたが持っている場合";
	var $mp_view_personal_homepage="私の個人的なホームページを参照するには、次のリンクをクリックしてください。：";
	var $mp_ctrlc_start="友人にQQ、MSNや電子メールを介して貼り付けたメッセージを、内容をコピーするためにクリック";
	var $mp_ctrlc_success="正常にコピーされ、Ctrl + Vキーを直接貼り付け";
	var $mp_ctrlc_failure="お使いのブラウザがコピーするCtrl + Cキーを使用して、自動コピー機能をサポートしていません";
	var $mp_all="全体";
	var $mp_add_you="友人としてあなたを追加する要求";
	var $mp_years="年";
	var $mp_over="上記";
	var $mp_province="県";
	var $mp_city="都市";
	
	var $mp_system_sends = "システムが送信します";
	var $mp_a_notice = "予告";
	var $mp_treatment_success = "治療成功";
	var $mp_treatment_failure = "処理に失敗しました";
	var $mp_select = "選択する";
	var $mp_cancel = "キャンセル";
	var $mp_delete = "削除";
	var $mp_generate_invite = "招待コードを生成";
	var $mp_invite_cost = "すべての招待コードの生成はあなたの費用がかかります";
	var $mp_integral = "ポイント";
	var $mp_surplus_integral = "あなたの現在の残りのポイント";
	var $mp_invitation_code_period = "注：招待コードは、の生成に有効である";
	var $mp_in_hours = "時間以内";
	var $mp_begin_to = "作るようになった";
	var $mp_invite_code_error = "招待コードはエラーを生成";
	var $mp_congratulations_invite_code = "おめでとうは、招待コードが生成されます：";


    var $mp_all_members="全てのメンバー";
    var $mp_online_members="オンライン";
    var $mp_new_members="最新のメンバー";
    var $mp_search_members="検索メンバー";
    var $mp_xingzuo="星座速配";
    var $mp_online_num="目前共有{online_num}人在线！在线会员每5分钟更新一次！";

	var $mp_quanxian='充電およびアップグレードを受ける権利をブラウズしてください';
	var $mp_noyear='不明年齢';
	
	var $mp_success='正常に削除';
	
};
?>