<?php
class bloglp{
	var $b_blog="블로그";
	var $b_mine="내 블로그";
	var $b_friend="친구 블로그";
	var $b_creat="새 블로그";
	var $b_edit="편집자";
	var $b_lock="로그는 잠겨 있습니다";
	var $b_search="블로그 검색";
	var $b_re_list="블로그 목록으로 돌아 가기";
	var $b_scan="블로그를 읽고";
	var $b_add_suc="성공적인 블로그를 제출";
	var $b_add_fal="블로그를 제출하지 않을 경우, 다시 제출하시기 바랍니다";
	var $b_edit_suc="블로그 성공을 수정!";
	var $b_edit_false="수정 블로그 실패!";
	var $b_del_suc="블로그의 성공을 삭제";
	var $b_del_false="블로그를 삭제하는 데 실패했습니다!";
	var $b_no_pass="각 옵션을 기입 해주세요";
	var $b_manage_sort="블로그 분류";
	var $b_def_sort="기본 카테고리 (편집 및 삭제를 지원하지 않습니다)";
	var $b_del_sort_suc="분류의 성공을 삭제";
	var $b_change_sort_suc="분류의 성공을 수정";
	var $b_change_sort_false="분류를 수정하지 못했습니다";
	var $b_only_fri_com="단지 저자의 친구 댓글";
	var $b_not_com="이 블로그는 언급을하지 않습니다";
	var $b_num="있다{num}기사 블로그";
	var	$b_title="표제";
	var $b_sort="분류";
	var $b_author="저자";
	var $b_default_sort="기본 카테고리";
	var $b_com_num="논평({b_com_num})";
	var $b_read_num="읽기({b_read_num})";
	var $b_no_fri_blog="죄송합니다, 아직이 당신의 블로그를 볼 수 있습니다";
	var $b_del="삭제";
	var $b_a_del="삭제?";
	var $b_button_save="저장";
	var $b_button_cancel="취소";
	var $b_none="당신은 블로그를 추가하지 않은,<a href='modules.php?app=blog_edit'>블로그 만들기</a>,또는<a href='modules.php?app=blog_friend'>친구의 블로그를 찾아</a>";
	var $b_limit="능력";
	var $b_same_sort="블로그의 분류 확인";
	var $b_public="공공의";
	var $b_private="는 자신의";
	var $b_pals="친구 만";
	var $b_error="당신은이 페이지를 방문 정보가 존재하지 않습니다";
	var $b_empty="정보를 입력 해주세요";
	var $b_limit_blog="블로그 권한을 설정, 당신은에 액세스 할 수 없습니다";
	var $b_they_com="사용자 리뷰";
	var $b_send_time="에 게시:{date_time}";
	var $b_i_com="내가 코멘트 할";
	var $b_button_re="대답";
	var $b_button_clear="제거";
	var $b_add_sort="카테고리 추가";
	var $b_content="만족";
	var $b_pic="그림";
	var $b_sel_album="（이미지 선택 앨범에서 직접 업로드）";
	var $b_button_sure="결정";
	var $b_empty_t="제목에 기입 해주세요";
	var $b_empty_content="내용을 기입 해주세요";
	var $b_his_blog="{holder}블로그";
	var $b_re_suc="성공적인 댓글";
	var $b_re_last="이전으로 돌아 가기";
	var $b_face="표현";
	var $b_pri="개인 정보 보호 정책";
	
	var $b_content_not_saved="귀하의 입력은 저장되지 않은!";
	var $b_label="꼬리표";
	var $b_set_permissions="액세스 권한 설정";
	var $b_data_loading="로딩 중, 잠시 기다려주십시오...";
	var $b_share="주";
	var $b_report="보고서";	
	var $b_right_set_competence="오른쪽 액세스 권한을 설정합니다";
	var $b_write_new_log = "새 블로그를 쓴";
	var $b_write_new_ask = "새로운 질문하기";
	var $b_write_ask_re = "답변";
	var $b_write_ask_qu = "제기 된 질문";
	
};
?>