<?php
class mypalslp{
	var $translate_s="가장 낮은 환불 1 골드에이 기능을 사용하여";
	var $mp_mypals="친구의 원";
	var $mp_list="친구 목록";
	var $mp_re_list="반환 친구 목록";
	var $mp_re_search="친구는 반환을 조회";
	var $mp_req="친구 신청";
	var $mp_invite="친구 초대하기";
	var $mp_add="친구 추가";
	var $mp_find="친구 찾기";
	var $mp_req_false="신청서를 제출하지 못했습니다,다시 제출하십시오";
	var $mp_not_self="자신을 친구로 추가 할 수 없습니다";
	var $mp_rep_req="사용자는리스트를 가지고";
	var $mp_info_wrong="정보의 오류, 친구를 추가하기 전에 확인하시기 바랍니다";
	var $mp_suc_reg="신청서를 제출했다";
	var $mp_suc_add="친구가 성공적으로 추가";
	var $mp_suc_del="성공적으로 삭제";
	var $mp_act_suc="성공적인 운영";
	var $mp_ref_add="사용자는 추가 요청을 거부";
	var $mp_no_pals=",당신은 친구가 아냐<a href='modules.php?app=mypals_search'>친구 찾기</a>";
	var $mp_del_req="응용 프로그램을 삭제";
	var $mp_con_del_req="당신은 당신이 친구 요청을 삭제 하시겠습니까?";
	var $mp_def_ico="기본 아바타";
	var $mp_name="사용자 이름";
	var $mp_con_tool="통신 도구";
	var $mp_mypals_state="친구의 상태";
	var $mp_wait_confirm="응용 프로그램 확인 아직 발행 된";
	var $mp_other_confirm="친구는 확인 된";
	var $mp_both_confirm="친구와 상호 인정";
	var $mp_a_del="당신은 당신이 친구를 삭제 하시겠습니까?";
	var $mp_en_home="홈 입력";
	var $mp_send_scrip="종이의 작은 조각을 보내기";
	var $mp_no_req="아직 응용 프로그램을받지 못한,<a href='modules.php?app=mypals_search'>친구 찾기</a>";
	var $mp_del="친구를 제거";
	var $mp_req_time="응용 프로그램 시간";
	var $mp_ctrl="운영";
	var $mp_req_name="응용 프로그램 사용자";
	var $mp_both_pal="친구에게 넥타이에 합의";
	var $mp_other_pal="동의";
	var $mp_ref_pal="거절";
	var $mp_age="시대";
	var $mp_empty_search="쿼리 정보는 비워 둘 수 없습니다";
	var $mp_online_search="온라인에게 찾기";
	var $mp_name_search="이름으로 친구 찾기";
	var $mp_area_search="지리적 찾기 친구";
	var $mp_man="남성";
	var $mp_woman="여성";
	var $mp_third_man="그";
	var $mp_third_woman="그녀";
	var $mp_sex="섹스";
	var $mp_reside="위치";
	var $mp_birth="고향";
	var $mp_country="국가";
	var $mp_no_search="당신은 사용자가 원하는 정보를 찾을 수 없습니다,<a href='modules.php?app=mypals_search'>새로운 검색</a>";
	var $mp_search_none="미안 해요，당신은 사용자가 원하는 정보를 찾을 수 없습니다";
	var $mp_add_mypals="플러스{he}친구";
	var $mp_scrip="에{he}종이의 작은 조각을 보내기";
	var $mp_unset="설정되지 않음";
	var $mp_more="더";
	var $mp_sort="친구 그룹";
	var $mp_m_sort="그룹 관리";
	var $mp_s_sort="그룹을 선택";
	var $mp_no_sort="그룹 해제";
	var $mp_def_sort="기본 그룹";
	var $mp_add_sort="그룹 추가";
	var $mp_t_sort="추가";
	var $mp_sort_pals="이 그룹에 친구가 없음";
	var $mp_whole="모든 친구";
	var $mp_p_sel="선택하세요";
	var $mp_height="신장";
	var $mp_income="수입";
	var $mp_sort_wrong="카테고리 이름을 기입 해주세요";
	var $mp_import_name="당신은 친구를 찾고자하는 이름을 입력하십시오";
	var $mp_remind="{num}응용 프로그램 친구";
	var $mp_none_search="미안 해요，친구는이를 찾을 수 없습니다";
	var $mp_select_sort="그룹을 선택";
	var $mp_search="수색";
	var $mp_search_cond="검색 기준을 선택하십시오";
	var $mp_online="온라인으로";
	var $mp_none_limit="한정";
	
	var $mp_pal_recomment = "추천";
	var $mp_pal_birth = "친구 생일";
	var $mp_pal_nofri = "어떤 친구 생일 없습니다";
	var $mp_invite_more="더 많은 친구와 가입하는 동료를 초대";
	var $mp_instant_ct_link="당신은 QQ 수、MSN 등 IM 도구，또는 전자 메일을 보내，당신의 친구를 말하려면 아래 링크，인치에 가입하도록 초대。";
	var $mp_instant_ct_send="또한 수정하거나 직접 클릭 할 수 있습니다“부”누름 단추，QQ에 의해 아래의 간단한 초대、MSN 또는 전자 우편 더 많은 친구에게 보낼。";
	var $mp_brief_invitation="단편 초청";
	var $mp_i="내가했다";
	var $mp_invite_you="개인 홈페이지의 스타일，당신이 초대 내 친구가。";
	var $mp_contact_me="내 친구에 추가，내 개인 홈페이지를 통해 나의 상황을 알 수 있습니다，내 사진을 공유하기，저와 연락。";
	var $mp_invited_postscript="포스트 스크립트 초대：";
	var $mp_links_invite="다음 링크를 클릭，친구 초대를 수락：";
	var $mp_if_you_have="만약 당신이";
	var $mp_view_personal_homepage="홈페이지，내 개인 홈 페이지를 보려면 다음 링크를 클릭하십시오：";
	var $mp_ctrlc_start="의 내용을 복사하기 클릭，QQ를 통해 메시지를 붙여 넣기、MSN 또는 친구에게 이메일 보내기";
	var $mp_ctrlc_success="복사 성공,Ctrl + V를 직접 붙여";
	var $mp_ctrlc_failure="브라우저가 자동으로 복사 기능을 지원하지 않는다，복사 Ctrl + C를 사용하십시오";
	var $mp_all="전체의";
	var $mp_add_you="당신을 친구로 추가 요청";
	var $mp_years="년";
	var $mp_over="위";
	var $mp_province="주";
	var $mp_city="도시";
	
	var $mp_system_sends = "시스템은 전송";
	var $mp_a_notice = "예고";
	var $mp_treatment_success = "치료 성공";
	var $mp_treatment_failure = "처리 실패";
	var $mp_select = "선택";
	var $mp_cancel = "취소";
	var $mp_delete = "삭제";
	var $mp_generate_invite = "초대 코드를 생성";
	var $mp_invite_cost = "모든 초대 코드 생성은 당신에게 비용";
	var $mp_integral = "통합";
	var $mp_surplus_integral = "에 대한 현재 남아있는 점";
	var $mp_invitation_code_period = "주의：초대 코드의 생성에 대해 유효";
	var $mp_in_hours = "시간 이내에";
	var $mp_begin_to = "생산하기 시작했다";
	var $mp_invite_code_error = "초대 코드에서 오류가 발생합니다";
	var $mp_congratulations_invite_code = "축하합니다, 당신의 초대 코드가 생성됩니다：";


    var $mp_all_members="모든 회원";
    var $mp_online_members="온라인으로";
    var $mp_new_members="가장 최근 멤버";
    var $mp_search_members="회원 검색";
    var $mp_xingzuo="별자리 일치";
    var $mp_online_num="현재이있다{online_num}온라인으로！온라인은 5 분마다 업데이트됩니다";
	var $mp_quanxian='검색 할 권리가 없습니다 재충전하고 업그레이드하십시오';
	var $mp_noyear='알 수없는 나이';
	
	var $mp_success='성공적으로 삭제';
	
};
?>