<?php
class bloglp{
	var $b_blog="Tagebuch";
	var $b_mine="Mein Tagebuch";
	var $b_friend="Freunde Tagebuch";
	var $b_creat="Das neue Tagebuch";
	var $b_edit="Editor";
	var $b_lock="Das Tagebuch wurde gesperrt";
	var $b_search="Tagebuch suchen";
	var $b_re_list="Zurück zur Liste Tagebuch";
	var $b_scan="Durchsuchen Tagebuch";
	var $b_add_suc="Senden Tagebuch Erfolg";
	var $b_add_fal="Tagebuch Vorlage gescheitert,Wiedervorlage";
	var $b_edit_suc="Ändern Tagebuch Erfolg!";
	var $b_edit_false="Fehler beim Tagebuch ändern!";
	var $b_del_suc="Löschen Tagebuch Erfolg";
	var $b_del_false="Löschen Tagebuch Ausfall!";
	var $b_no_pass="Bitte füllen Sie jede Option";
	var $b_manage_sort="Tagebuch Klassifizierung";
	var $b_def_sort="Default Category (Unterstützt nicht Bearbeiten und Löschen)";
	var $b_del_sort_suc="Löschen Klassifizierung Erfolg";
	var $b_change_sort_suc="Ändern Sie die Klassifizierung Erfolg";
	var $b_change_sort_false="Klassifizierung nicht";
	var $b_only_fri_com="Sie haben keine Berechtigung zur Stellungnahme";
	var $b_not_com="Dieses Tagebuch kann nicht kommentieren";
	var $b_num="haben{num}Tagebuch";
	var	$b_title="Titel";
	var $b_sort="Klassifikation";
	var $b_author="Autor";
	var $b_default_sort="Default Category";
	var $b_com_num="Kommentar({b_com_num})";
	var $b_read_num="lesen({b_read_num})";
	var $b_no_fri_blog="tut mir leid，Kein Tagebuch sehen können";
	var $b_del="löschen";
	var $b_a_del="OK, um zu löschen?";
	var $b_button_save="sparen";
	var $b_button_cancel="stornieren";
	var $b_none="Sie haben nicht Tagebuch hinzufügen,<a href='modules.php?app=blog_edit'>erstellen Sie einen Login</a>,oder<a href='modules.php?app=blog_friend'>Siehe Freunden Tagebuch</a>";
	var $b_limit="Kompetenz";
	var $b_same_sort="Schauen Sie in der gleichen Kategorie Tagebuch";
	var $b_public="Öffentlichkeit";
	var $b_private="Nur ihre eigenen";
	var $b_pals="Nur Freunde";
	var $b_error="Informationen besuchen Sie die Seite existiert nicht";
	var $b_empty="Bitte füllen Sie die Informationen";
	var $b_limit_blog="Tagebuch über die Berechtigung，Sie können nicht auf";
	var $b_they_com="Testberichte";
	var $b_send_time="Verfasst um:{date_time}";
	var $b_i_com="Ich möchte einen Kommentar";
	var $b_button_re="antworten";
	var $b_button_clear="entfernen";
	var $b_add_sort="hinzufügen";
	var $b_content="Inhalt";
	var $b_pic="Bild";
	var $b_sel_album="（Wählen Sie Bild aus dem Album hochgeladen direkt）";
	var $b_button_sure="bestimmen";
	var $b_empty_t="Bitte füllen Sie in der Titel";
	var $b_empty_content="Bitte füllen Sie die Inhalte";
	var $b_his_blog="{holder}Tagebuch";
	var $b_re_suc="Kommentare erfolgreich";
	var $b_re_last="Rückkehr zum vorherigen";
	var $b_face="Ausdruck";
	var $b_pri="Ruhe";
	
	var $b_content_not_saved="Ihre Eingabe konnte nicht gespeichert werden!";
	var $b_label="Anhänger";
	var $b_set_permissions="Set Zugriffsberechtigungen";
	var $b_data_loading="Lade, bitte warten...";
	var $b_share="Aktie";
	var $b_report="Bericht";	
	var $b_right_set_competence="Rechts klicken, um Zugriffsrechte gesetzt";
	var $b_write_new_log = "Schreiben Sie eine neue Tagebuch";
	var $b_write_new_ask = "Stellen Sie Fragen";
	var $b_write_ask_re = "Antwort";
	var $b_write_ask_qu = "Fragen aufgeworfen";
	
};
?>