<?php
class mypalslp{
	var $translate_s="Verwenden Sie diese Funktion auf die niedrigste Charge 1 Gold";
	var $mp_mypals="Kreis der Freunde";
	var $mp_list="Freunde-Liste";
	var $mp_re_list="Versandkosten Freundesliste";
	var $mp_re_search="Zurück Abfrage";
	var $mp_req="Anwendung";
	var $mp_invite="Freund einladen";
	var $mp_add="Freund hinzufügen";
	var $mp_find="Freunde finden";
	var $mp_req_false="Nichtanwendungsinformationen zu senden bitte erneut";
	var $mp_not_self="Kann dich nicht selbst als Freund hinzufügen";
	var $mp_rep_req="Der Benutzer hat die Liste";
	var $mp_info_wrong="Informationen Fehler,Prüfen und fügen";
	var $mp_suc_reg="Hat einen Antrag eingereicht";
	var $mp_suc_add="Freunde erfolgreich hinzugefügt";
	var $mp_suc_del="erfolgreich gelöscht";
	var $mp_act_suc="Der erfolgreiche Betrieb";
	var $mp_ref_add="Der Benutzer bestreitet Anfrage hinzufügen";
	var $mp_no_pals="Keine Freunde,<a href='modules.php?app=mypals_search'>Freunde finden</a>";
	var $mp_del_req="Antrag auf Entfernung";
	var $mp_con_del_req="Sind Sie sicher, dass Sie diese Freundschaftsanfragen löschen möchten?";
	var $mp_def_ico="Standard-Avatar";
	var $mp_name="Benutzername";
	var $mp_con_tool="Kommunikationswerkzeuge";
	var $mp_mypals_state="Freunde Status";
	var $mp_wait_confirm="Anwendung wurde noch ausgestellt bestätigt";
	var $mp_other_confirm="Freunde haben sich bestätigt";
	var $mp_both_confirm="Freunde und gegenseitig anerkannt";
	var $mp_a_del="Sind Sie sicher, dass Sie diesen Freund löschen möchten?";
	var $mp_en_home="Geben Sie Start";
	var $mp_send_scrip="Senden Sie ein kleines Stück Papier";
	var $mp_no_req="Sie haben noch kein Antrag eingegangen,<a href='modules.php?app=mypals_search'>Freunde finden</a>";
	var $mp_del="Freunde entfernen";
	var $mp_req_time="Verarbeitungszeit";
	var $mp_ctrl="Ausführung";
	var $mp_req_name="Anwendungsbenutzer";
	var $mp_both_pal="Vereinbart, es an einen Freund binden";
	var $mp_other_pal="zustimmen";
	var $mp_ref_pal="Ablehnung";
	var $mp_age="Alter";
	var $mp_empty_search="Abfrageinformationen darf nicht leer sein";
	var $mp_online_search="Online suchen";
	var $mp_name_search="Finden Sie Freunde nach Namen";
	var $mp_area_search="Geographische Freunde finden";
	var $mp_man="männlich";
	var $mp_woman="weiblich";
	var $mp_third_man="er";
	var $mp_third_woman="sie";
	var $mp_sex="gender";
	var $mp_reside="Lage";
	var $mp_birth="Heimatstadt";
	var $mp_country="Land";
	var $mp_no_search="Haben Sie nicht gefunden, was Sie für die Benutzer suchen,<a href='modules.php?app=mypals_search'>Neue Suche</a>";
	var $mp_search_none="Sorry, nicht das finden, was Sie für die Benutzer suchen";
	var $mp_add_mypals="{he}Als Freund hinzufügen";
	var $mp_scrip="{he}Senden Sie ein kleines Stück Papier";
	var $mp_unset="Nicht festgelegt";
	var $mp_more="mehr";
	var $mp_sort="Gruppierung";
	var $mp_m_sort="Konzernlage";
	var $mp_s_sort="Gruppe auswählen";
	var $mp_no_sort="Ungrouped";
	var $mp_def_sort="Default";
	var $mp_add_sort="hinzufügen einer Gruppe";
	var $mp_t_sort="hinzufügen";
	var $mp_sort_pals="Keine Freunde in dieser Gruppe";
	var $mp_whole="Alle Freunde";
	var $mp_p_sel="Bitte wählen Sie";
	var $mp_height="Höhe";
	var $mp_income="Einkommen";
	var $mp_sort_wrong="Bitte füllen Sie den Namen der Kategorie";
	var $mp_import_name="Bitte geben Sie den Namen ein, um einen Freund finden wollen";
	var $mp_remind="{num}Freundschaftsanfrage";
	var $mp_none_search="Sorry, nicht einen Freund zu finden diese";
	var $mp_select_sort="Gruppe auswählen";
	var $mp_search="Suche";
	var $mp_search_cond="Bitte wählen Sie Ihre Suchkriterien";
	var $mp_online="Online";
	var $mp_none_limit="ohne Einschränkung der";
	
	var $mp_pal_recomment = "empfehlen ";
	var $mp_pal_birth = "Freunde Geburtstag";
	var $mp_pal_nofri = "Keine Freunde Geburtstag";
	var $mp_invite_more="Lade weitere Freunde und Kollegen zu verbinden";
	var $mp_instant_ct_link="Sie können QQ, MSN und andere IM-Tools oder senden Sie eine E-Mail, Link unten an deine Freunde sagen, laden sie zum Mitmachen。";
	var $mp_instant_ct_send="Sie können auch direkt ändern oder klicken Sie auf die Schaltfläche 'Kopieren', um kurze Einladung zu senken QQ, MSN oder E-Mail schicken, um mehr Freunde。";
	var $mp_brief_invitation="Einladung";
	var $mp_i="Ich war";
	var $mp_invite_you="Gegründet eine persönliche Homepage, lädt Sie ein, beizutreten und mein Freund。";
	var $mp_contact_me="Zu meinen Freunden hinzufügen, können Sie durch meine persönliche Homepage meiner Situation lernen können, um meine Fotos zu teilen, in Kontakt zu bleiben mit mir。";
	var $mp_invited_postscript="Einladung Worte：";
	var $mp_links_invite="Klicken Sie auf den Link unten, um zu erhalten ein Freund einladen：";
	var $mp_if_you_have="Wenn Sie";
	var $mp_view_personal_homepage="Auf Konto, klicken Sie bitte auf den folgenden Link, um meine persönlichen Startseite sehen：";
	var $mp_ctrlc_start="Klicken Sie hier um den Inhalt, Einfügen Nachrichten durch QQ, MSN oder E-Mail an einen Freund schicken";
	var $mp_ctrlc_success="Erfolgreich kopiert, Strg + V einfügen direkt";
	var $mp_ctrlc_failure="Ihr Browser unterstützt keine Auto-Copy-Funktion können Sie Strg + C zum Kopieren";
	var $mp_all="ganze";
	var $mp_add_you="Anfrage an Sie als Freund hinzufügen";
	var $mp_years="Alter";
	var $mp_over="oben";
	var $mp_province="Provinz";
	var $mp_city="City";
	
	var $mp_system_sends = "Das System sendet";
	var $mp_a_notice = "Bekanntmachung";
	var $mp_treatment_success = "Die erfolgreiche Umsetzung";
	var $mp_treatment_failure = "Verarbeitung gescheitert";
	var $mp_select = "wählen";
	var $mp_cancel = "stornieren";
	var $mp_delete = "löschen";
	var $mp_generate_invite = "Generieren Einladungscode";
	var $mp_invite_cost = "Jede Einladung Code Generation kostet";
	var $mp_integral = "Integration";
	var $mp_surplus_integral = "Ihre aktuelle Restpunkte für die";
	var $mp_invitation_code_period = "Hinweis: Die Einladung Code ist gültig für die Erzeugung von";
	var $mp_in_hours = "innerhalb von Stunden";
	var $mp_begin_to = "fing an zu produzieren";
	var $mp_invite_code_error = "Einladung Code erzeugt einen Fehler";
	var $mp_congratulations_invite_code = "Herzlichen Glückwunsch, Ihre Einladung Code generiert：";


    var $mp_all_members="Alle Mitglieder";
    var $mp_online_members="Online Mitglieder";
    var $mp_new_members="Neueste Mitglieder";
    var $mp_search_members="Benutzer suchen";
    var $mp_xingzuo="星座速配";
    var $mp_online_num="目前共有{online_num}人在线！在线会员每5分钟更新一次！";

	var $mp_quanxian='Kann nicht finden, wirf bitte aktualisieren';
	var $mp_noyear='Alter unbekannt';
	
	var $mp_success='erfolgreich gelöscht';
	
};
?>